#!/bin/sh
echo "Running linter..."
uv run ruff check . --fix . && uv run ruff format .

if [ $? -ne 0 ]; then
  echo "Lint failed, push aborted."
  exit 1
fi

if ! git diff --quiet; then
  echo "Lint auto-fixed some files. Push aborted."
  exit 1
fi