#!/bin/sh
echo "Running linter..."
uv run ruff check . --fix . && uv run ruff format .

if [ $? -ne 0 ]; then
  echo "Push aborted: Lint failed."
  exit 1
fi

if ! git diff --quiet; then
  echo "Push aborted: Found uncommitted files. Were they changed by the linter?"
  exit 1
fi