from src.api.metadata.common.schema import yahoo_chart

b3_listagem = [
    "b3_listagem.setor",
    "b3_listagem.subsetor",
    "b3_listagem.segmento",
    "b3_listagem.segmento_de_negociacao",
]

yahoo_target = [
    "yahoo_target.min",
    "yahoo_target.avg",
    "yahoo_target.max",
]

yahoo_recom = [
    "yahoo_recom.strong_buy",
    "yahoo_recom.buy",
    "yahoo_recom.hold",
    "yahoo_recom.sell",
    "yahoo_recom.strong_sell",
]

tradingview = [
    "tradingview.rating.strong_buy",
    "tradingview.rating.buy",
    "tradingview.rating.hold",
    "tradingview.rating.sell",
    "tradingview.rating.strong_sell",
    "tradingview.forecast.min",
    "tradingview.forecast.avg",
    "tradingview.forecast.max",
]

simplywall = [
    "simplywall.value",
    "simplywall.future",
    "simplywall.past",
    "simplywall.health",
    "simplywall.dividend",
]

statusinvest = [
    "statusinvest.preco",
    "statusinvest.dy",
    "statusinvest.p_l",
    "statusinvest.p_vp",
    "statusinvest.p_ativos",
    "statusinvest.margem_bruta",
    "statusinvest.margem_ebit",
    "statusinvest.marg_liquida",
    "statusinvest.p_ebit",
    "statusinvest.ev_ebit",
    "statusinvest.divida_liquida_ebit",
    "statusinvest.div_liq_patri",
    "statusinvest.psr",
    "statusinvest.p_cap_giro",
    "statusinvest.p_at_cir_liq",
    "statusinvest.liq_corrente",
    "statusinvest.roe",
    "statusinvest.roa",
    "statusinvest.roic",
    "statusinvest.patrimonio_ativos",
    "statusinvest.passivos_ativos",
    "statusinvest.giro_ativos",
    "statusinvest.cagr_receitas_5_anos",
    "statusinvest.cagr_lucros_5_anos",
    "statusinvest.liquidez_media_diaria",
    "statusinvest.vpa",
    "statusinvest.lpa",
    "statusinvest.peg_ratio",
    "statusinvest.valor_de_mercado",
]

investidor10 = [
    "investidor10.rentabilidade.nominal.1_mes",
    "investidor10.rentabilidade.nominal.3_meses",
    "investidor10.rentabilidade.nominal.1_ano",
    "investidor10.rentabilidade.nominal.2_anos",
    "investidor10.rentabilidade.nominal.5_anos",
    "investidor10.rentabilidade.nominal.10_anos",
    "investidor10.rentabilidade.real.1_mes",
    "investidor10.rentabilidade.real.3_meses",
    "investidor10.rentabilidade.real.1_ano",
    "investidor10.rentabilidade.real.2_anos",
    "investidor10.rentabilidade.real.5_anos",
    "investidor10.rentabilidade.real.10_anos",
    "investidor10.fundamentos.p_l",
    "investidor10.fundamentos.p_receita_psr",
    "investidor10.fundamentos.p_vp",
    "investidor10.fundamentos.dividend_yield_bbdc4",
    "investidor10.fundamentos.payout",
    "investidor10.fundamentos.margem_liquida",
    "investidor10.fundamentos.margem_bruta",
    "investidor10.fundamentos.margem_ebit",
    "investidor10.fundamentos.ev_ebit",
    "investidor10.fundamentos.p_ebit",
    "investidor10.fundamentos.p_ativo",
    "investidor10.fundamentos.p_cap_giro",
    "investidor10.fundamentos.p_ativo_circ_liq",
    "investidor10.fundamentos.vpa",
    "investidor10.fundamentos.lpa",
    "investidor10.fundamentos.giro_ativos",
    "investidor10.fundamentos.roe",
    "investidor10.fundamentos.roic",
    "investidor10.fundamentos.roa",
    "investidor10.fundamentos.patrimonio_ativos",
    "investidor10.fundamentos.passivos_ativos",
    "investidor10.fundamentos.liquidez_corrente",
    "investidor10.fundamentos.cagr_receitas_5_anos",
    "investidor10.fundamentos.cagr_lucros_5_anos",
    "investidor10.cadastral.nome_da_empresa",
    "investidor10.cadastral.cnpj",
    "investidor10.cadastral.ano_de_estreia_na_bolsa",
    "investidor10.cadastral.numero_de_funcionarios",
    "investidor10.cadastral.ano_de_fundacao",
    "investidor10.cadastral.papeis_da_empresa",
    "investidor10.cadastral.papeis_fracionados",
    "investidor10.financeiro.valor_de_mercado",
    "investidor10.financeiro.valor_de_firma",
    "investidor10.financeiro.patrimonio_liquido",
    "investidor10.financeiro.numero_total_de_papeis",
    "investidor10.financeiro.ativos",
    "investidor10.financeiro.ativo_circulante",
    "investidor10.financeiro.disponibilidade",
    "investidor10.financeiro.segmento_de_listagem",
    "investidor10.financeiro.free_float",
    "investidor10.financeiro.tag_along",
    "investidor10.financeiro.liquidez_media_diaria",
    "investidor10.financeiro.setor",
    "investidor10.financeiro.segmento",
]

all = b3_listagem + yahoo_chart + yahoo_target + yahoo_recom + tradingview + simplywall + statusinvest + investidor10
