CREATE TABLE tickers (
    ticker TEXT PRIMARY KEY NOT NULL,
    last_requested DATETIME NOT NULL
);

INSERT INTO tickers (ticker, last_requested) VALUES
('VALE3', CURRENT_TIMESTAMP),
('ITUB4', CURRENT_TIMESTAMP),
('PETR4', CURRENT_TIMESTAMP),
('BBDC4', CURRENT_TIMESTAMP);