CREATE TABLE tickers (
    ticker TEXT PRIMARY KEY NOT NULL,
    last_requested DATETIME NOT NULL
);

INSERT INTO tickers (ticker, last_requested) VALUES
('VALE3', CURRENT_TIMESTAMP),
('ITUB4', CURRENT_TIMESTAMP),
('PETR4', CURRENT_TIMESTAMP),
('BBDC4', CURRENT_TIMESTAMP);

-- ('VALE3', CURRENT_TIMESTAMP),
-- ('ITUB4', CURRENT_TIMESTAMP),
-- ('PETR4', CURRENT_TIMESTAMP),
-- ('PETR3', CURRENT_TIMESTAMP),
-- ('BBDC4', CURRENT_TIMESTAMP),
-- ('SBSP3', CURRENT_TIMESTAMP),
-- ('ELET3', CURRENT_TIMESTAMP),
-- ('B3SA3', CURRENT_TIMESTAMP),
-- ('ITSA4', CURRENT_TIMESTAMP),
-- ('EMBR3', CURRENT_TIMESTAMP),
-- ('BBAS3', CURRENT_TIMESTAMP),
-- ('BPAC11', CURRENT_TIMESTAMP),
-- ('ABEV3', CURRENT_TIMESTAMP),
-- ('WEGE3', CURRENT_TIMESTAMP),
-- ('EQTL3', CURRENT_TIMESTAMP),
-- ('RDOR3', CURRENT_TIMESTAMP),
-- ('SUZB3', CURRENT_TIMESTAMP),
-- ('RENT3', CURRENT_TIMESTAMP),
-- ('PRIO3', CURRENT_TIMESTAMP);